[package]
name = "cosi-db"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rocket = { version = "0.5.0-rc.2", features = ["secrets"] }
async-trait = "0.1.56"
mongodb = "2.2"
chrono = "0.4.0"
