version: '3'
services:
  cosi-db:
    build: .
    ports:
      - 27017:27017
      - 8000:8000
    volumes:
      - .:/mnt/cosi
    command: bash -c "cd /mnt/cosi && cargo run"
    network_mode: "host"
  mongodb:
    image: mongo:5.0
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
      - MONGO_INITDB_DATABASE=cosi_db
    network_mode: "host"
