name: actions
on: [pull_request]
concurrency: 
  group: ${{ github.ref }}
  cancel-in-progress: true
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: hecrj/setup-rust-action@v1
        with:
          rust-version: 1.62
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.7.0
        with:
          mongodb-version: 5.0
      - name: Build
        run: |
          cargo build
      - name: Test Server
        run: |
          cargo run &
          sleep 5 &&
          cd tests &&
          npm install &&
          npm test
