name: actions
on: [pull_request]
concurrency: 
  group: ${{ github.ref }}
  cancel-in-progress: true
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Test Server
        run: |
          docker-compose up -d 
          cd tests 
          npm install
          npm test
